-- Create Monuments table if it doesn't exist
CREATE TABLE IF NOT EXISTS tours."Monuments" (
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "YearOfCreation" integer NOT NULL,
    "Status" integer NOT NULL,
    "Latitude" double precision NOT NULL,
    "Longitude" double precision NOT NULL,
    CONSTRAINT "PK_Monuments" PRIMARY KEY ("Id")
);

-- Create Notifications table if it doesn't exist (for Tours module)
CREATE TABLE IF NOT EXISTS tours."Notifications" (
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "UserId" bigint NOT NULL,
    "Title" text NOT NULL,
    "Preview" text NOT NULL,
    "ProblemId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "IsRead" boolean NOT NULL DEFAULT false,
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id")
);

-- Create PublicPointRequests table if it doesn't exist
CREATE TABLE IF NOT EXISTS tours."PublicPointRequests" (
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "TourId" bigint NOT NULL,
    "KeyPointIndex" integer NOT NULL,
    "AuthorId" bigint NOT NULL,
    "Status" integer NOT NULL,
    "AdminComment" character varying(500),
    "CreatedAt" timestamp with time zone NOT NULL,
    "ProcessedAt" timestamp with time zone,
    CONSTRAINT "PK_PublicPointRequests" PRIMARY KEY ("Id")
);

-- Create ShoppingCarts table if it doesn't exist
CREATE TABLE IF NOT EXISTS tours."ShoppingCarts" (
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "TouristId" bigint NOT NULL,
    "TotalPrice" decimal(18,2) NOT NULL,
    CONSTRAINT "PK_ShoppingCarts" PRIMARY KEY ("Id")
);

-- Create OrderItems table if it doesn't exist
CREATE TABLE IF NOT EXISTS tours."OrderItems" (
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "TourId" bigint NOT NULL,
    "TourName" character varying(100) NOT NULL,
    "Price" decimal(18,2) NOT NULL,
    "ShoppingCartId" bigint,
    CONSTRAINT "PK_OrderItems" PRIMARY KEY ("Id")
);

-- Create TourDurations table if it doesn't exist
CREATE TABLE IF NOT EXISTS tours."TourDurations" (
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "TransportType" character varying(50) NOT NULL,
    "DurationInMinutes" integer NOT NULL,
    "TourId" bigint NOT NULL,
    CONSTRAINT "PK_TourDurations" PRIMARY KEY ("Id")
);

-- Create AnnualAwards table if it doesn't exist
CREATE TABLE IF NOT EXISTS tours."AnnualAwards" (
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Year" integer NOT NULL,
    "AuthorId" bigint NOT NULL,
    "TourId" bigint NOT NULL,
    "Status" integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_AnnualAwards" PRIMARY KEY ("Id")
);

-- Create indexes if they don't exist
CREATE UNIQUE INDEX IF NOT EXISTS "IX_ShoppingCarts_TouristId" ON tours."ShoppingCarts" ("TouristId");
