-- ===== Enhanced Reviews =====
CREATE TABLE IF NOT EXISTS tours."EnhancedReviews" (
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "TourId" bigint NOT NULL,
    "TouristId" bigint NOT NULL,
    "OverallRating" integer NOT NULL,
    "GuideQuality" integer NOT NULL,
    "ValueForMoney" integer NOT NULL,
    "RouteScenery" integer NOT NULL,
    "Difficulty" integer NOT NULL,
    "GroupSize" integer NOT NULL,
    "TextReview" character varying(2000),
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_EnhancedReviews" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS tours."EnhancedReviewPros" (
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "EnhancedReviewId" bigint NOT NULL,
    "Text" character varying(200) NOT NULL,
    CONSTRAINT "PK_EnhancedReviewPros" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EnhancedReviewPros_EnhancedReviews_EnhancedReviewId"
        FOREIGN KEY ("EnhancedReviewId") REFERENCES tours."EnhancedReviews" ("Id")
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tours."EnhancedReviewCons" (
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "EnhancedReviewId" bigint NOT NULL,
    "Text" character varying(200) NOT NULL,
    CONSTRAINT "PK_EnhancedReviewCons" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EnhancedReviewCons_EnhancedReviews_EnhancedReviewId"
        FOREIGN KEY ("EnhancedReviewId") REFERENCES tours."EnhancedReviews" ("Id")
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tours."EnhancedReviewTags" (
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "EnhancedReviewId" bigint NOT NULL,
    "Tag" integer NOT NULL,
    CONSTRAINT "PK_EnhancedReviewTags" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EnhancedReviewTags_EnhancedReviews_EnhancedReviewId"
        FOREIGN KEY ("EnhancedReviewId") REFERENCES tours."EnhancedReviews" ("Id")
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tours."EnhancedReviewImages" (
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "EnhancedReviewId" bigint NOT NULL,
    "Url" character varying(2048) NOT NULL,
    "SizeBytes" bigint NOT NULL,
    CONSTRAINT "PK_EnhancedReviewImages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EnhancedReviewImages_EnhancedReviews_EnhancedReviewId"
        FOREIGN KEY ("EnhancedReviewId") REFERENCES tours."EnhancedReviews" ("Id")
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tours."EnhancedReviewHelpfulVotes" (
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "EnhancedReviewId" bigint NOT NULL,
    "TouristId" bigint NOT NULL,
    "VotedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_EnhancedReviewHelpfulVotes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EnhancedReviewHelpfulVotes_EnhancedReviews_EnhancedReviewId"
        FOREIGN KEY ("EnhancedReviewId") REFERENCES tours."EnhancedReviews" ("Id")
        ON DELETE CASCADE
);

-- Indexes (stabilnost testova + isti kao u migraciji)
CREATE UNIQUE INDEX IF NOT EXISTS "IX_EnhancedReviews_TourId_TouristId"
    ON tours."EnhancedReviews" ("TourId", "TouristId");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_EnhancedReviewHelpfulVotes_EnhancedReviewId_TouristId"
    ON tours."EnhancedReviewHelpfulVotes" ("EnhancedReviewId", "TouristId");

CREATE INDEX IF NOT EXISTS "IX_EnhancedReviewPros_EnhancedReviewId"
    ON tours."EnhancedReviewPros" ("EnhancedReviewId");

CREATE INDEX IF NOT EXISTS "IX_EnhancedReviewCons_EnhancedReviewId"
    ON tours."EnhancedReviewCons" ("EnhancedReviewId");

CREATE INDEX IF NOT EXISTS "IX_EnhancedReviewTags_EnhancedReviewId"
    ON tours."EnhancedReviewTags" ("EnhancedReviewId");

CREATE INDEX IF NOT EXISTS "IX_EnhancedReviewImages_EnhancedReviewId"
    ON tours."EnhancedReviewImages" ("EnhancedReviewId");
