-- Create tours schema if it doesn't exist
CREATE SCHEMA IF NOT EXISTS tours;

-- Create Monuments table if it doesn't exist (needed for LocationService tests)
CREATE TABLE IF NOT EXISTS tours."Monuments" (
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "YearOfCreation" integer NOT NULL,
    "Status" integer NOT NULL,
    "Latitude" double precision NOT NULL,
    "Longitude" double precision NOT NULL,
    CONSTRAINT "PK_Monuments" PRIMARY KEY ("Id")
);

-- Insert test monuments data for LocationService tests
INSERT INTO tours."Monuments"("Id", "Name", "Description", "YearOfCreation", "Status", "Latitude", "Longitude")
VALUES 
    (-1, 'Kalemegdanska tvrðava', 'Istorijska tvrðava u Beogradu na ušæu Save u Dunav', 1403, 0, 44.8225, 20.4508),
    (-2, 'Petrovaradinska tvrðava', 'Tvrðava na Dunavu u Novom Sadu', 1692, 0, 45.2551, 19.8636),
    (-3, 'Manastir Studenica', 'Srednjovekovni manastir zadužbina Stefana Nemanje', 1190, 0, 43.4861, 20.5333)
ON CONFLICT ("Id") DO NOTHING;