-- Migration: Add ShoppingCart and OrderItem tables

-- Create ShoppingCarts table
CREATE TABLE IF NOT EXISTS tours."ShoppingCarts"
(
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TouristId" bigint NOT NULL,
    "TotalPrice" decimal(18,2) NOT NULL DEFAULT 0
);

-- Create unique index on TouristId (one cart per tourist)
CREATE UNIQUE INDEX IF NOT EXISTS "IX_ShoppingCarts_TouristId" 
ON tours."ShoppingCarts" ("TouristId");

-- Create OrderItems table
CREATE TABLE IF NOT EXISTS tours."OrderItems"
(
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TourId" bigint NOT NULL,
    "TourName" character varying(100) NOT NULL,
    "Price" decimal(18,2) NOT NULL DEFAULT 0,
    "ShoppingCartId" bigint NOT NULL,
    CONSTRAINT "FK_OrderItems_ShoppingCarts_ShoppingCartId" 
        FOREIGN KEY ("ShoppingCartId") 
        REFERENCES tours."ShoppingCarts" ("Id") 
        ON DELETE CASCADE
);

-- Create index on ShoppingCartId for faster queries
CREATE INDEX IF NOT EXISTS "IX_OrderItems_ShoppingCartId" 
ON tours."OrderItems" ("ShoppingCartId");
