// <auto-generated />
using Explorer.Encounters.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Explorer.Encounters.Infrastructure.Migrations
{
    [DbContext(typeof(EncountersContext))]
    partial class EncountersContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("encounters")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Explorer.Encounters.Core.Domain.Encounter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("Xp")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Encounters", "encounters");
                });

            modelBuilder.Entity("Explorer.Encounters.Core.Domain.Encounter", b =>
                {
                    b.OwnsOne("Explorer.Encounters.Core.Domain.GeoLocation", "Location", b1 =>
                        {
                            b1.Property<long>("EncounterId")
                                .HasColumnType("bigint");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("longitude");

                            b1.HasKey("EncounterId");

                            b1.ToTable("Encounters", "encounters");

                            b1.ToJson("Location");

                            b1.WithOwner()
                                .HasForeignKey("EncounterId");
                        });

                    b.OwnsOne("Explorer.Encounters.Core.Domain.HiddenLocationEncounter", "HiddenLocationDetails", b1 =>
                        {
                            b1.Property<long>("EncounterId")
                                .HasColumnType("bigint");

                            b1.Property<double>("ActivationRadiusMeters")
                                .HasColumnType("double precision")
                                .HasColumnName("activationRadiusMeters");

                            b1.Property<int>("DistanceMeters")
                                .HasColumnType("integer");

                            b1.Property<string>("ImageUrl")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("imageUrl");

                            b1.Property<int>("SecondsToViewPhoto")
                                .HasColumnType("integer");

                            b1.HasKey("EncounterId");

                            b1.ToTable("Encounters", "encounters");

                            b1.ToJson("HiddenLocationDetails");

                            b1.WithOwner()
                                .HasForeignKey("EncounterId");

                            b1.OwnsOne("Explorer.Encounters.Core.Domain.GeoLocation", "ActivationLocation", b2 =>
                                {
                                    b2.Property<long>("HiddenLocationEncounterEncounterId")
                                        .HasColumnType("bigint");

                                    b2.Property<double>("Latitude")
                                        .HasColumnType("double precision")
                                        .HasColumnName("activationLatitude");

                                    b2.Property<double>("Longitude")
                                        .HasColumnType("double precision")
                                        .HasColumnName("activationLongitude");

                                    b2.HasKey("HiddenLocationEncounterEncounterId");

                                    b2.ToTable("Encounters", "encounters");

                                    b2.WithOwner()
                                        .HasForeignKey("HiddenLocationEncounterEncounterId");
                                });

                            b1.OwnsOne("Explorer.Encounters.Core.Domain.GeoLocation", "PhotoLocation", b2 =>
                                {
                                    b2.Property<long>("HiddenLocationEncounterEncounterId")
                                        .HasColumnType("bigint");

                                    b2.Property<double>("Latitude")
                                        .HasColumnType("double precision")
                                        .HasColumnName("photoLatitude");

                                    b2.Property<double>("Longitude")
                                        .HasColumnType("double precision")
                                        .HasColumnName("photoLongitude");

                                    b2.HasKey("HiddenLocationEncounterEncounterId");

                                    b2.ToTable("Encounters", "encounters");

                                    b2.WithOwner()
                                        .HasForeignKey("HiddenLocationEncounterEncounterId");
                                });

                            b1.Navigation("ActivationLocation")
                                .IsRequired();

                            b1.Navigation("PhotoLocation")
                                .IsRequired();
                        });

                    b.Navigation("HiddenLocationDetails");

                    b.Navigation("Location")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
